server:
  name: "message"
  id: "message1"
  machine_id: 101
  port: 9999
consul:
  host: "127.0.0.1"
  port: 8500
mysql:
  host: "127.0.0.1"
  port: 3306
  user:
  password:
  db: "IM"
  max_connections: 10
  max_idle_connections: 5
redis:
  host: "127.0.0.1"
  port: 6379
  password:
  db: 0