// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protocol.proto
// Protobuf C++ Version: 5.29.3

#include "protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protocol {

inline constexpr Packet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        seq_{::uint64_t{0u}},
        timestamp_{::uint64_t{0u}},
        cmd_{0u},
        msg_type_{0u},
        data_length_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Packet::Packet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketDefaultTypeInternal() {}
  union {
    Packet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketDefaultTypeInternal _Packet_default_instance_;

inline constexpr MsgACK_S::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        seq_{::uint64_t{0u}},
        msg_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR MsgACK_S::MsgACK_S(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MsgACK_SDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgACK_SDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgACK_SDefaultTypeInternal() {}
  union {
    MsgACK_S _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgACK_SDefaultTypeInternal _MsgACK_S_default_instance_;

inline constexpr MsgACK_C::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        seq_{::uint64_t{0u}},
        conv_id_{::uint64_t{0u}},
        last_msg_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR MsgACK_C::MsgACK_C(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MsgACK_CDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgACK_CDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgACK_CDefaultTypeInternal() {}
  union {
    MsgACK_C _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgACK_CDefaultTypeInternal _MsgACK_C_default_instance_;

inline constexpr Msg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msg_id_{::uint64_t{0u}},
        conversation_id_{::uint64_t{0u}},
        sender_id_{::uint64_t{0u}},
        receiver_id_{::uint64_t{0u}},
        content_type_{0u},
        is_group_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Msg::Msg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgDefaultTypeInternal() {}
  union {
    Msg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgDefaultTypeInternal _Msg_default_instance_;

inline constexpr GroupMsgNotify::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : group_id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GroupMsgNotify::GroupMsgNotify(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GroupMsgNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GroupMsgNotifyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroupMsgNotifyDefaultTypeInternal() {}
  union {
    GroupMsgNotify _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroupMsgNotifyDefaultTypeInternal _GroupMsgNotify_default_instance_;
}  // namespace protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_protocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.seq_),
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.cmd_),
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.msg_type_),
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.data_length_),
        PROTOBUF_FIELD_OFFSET(::protocol::Packet, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.msg_id_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.conversation_id_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.sender_id_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.receiver_id_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.content_type_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.is_group_),
        PROTOBUF_FIELD_OFFSET(::protocol::Msg, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_C, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_C, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_C, _impl_.seq_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_C, _impl_.conv_id_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_C, _impl_.last_msg_id_),
        ~0u,
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_S, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_S, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_S, _impl_.seq_),
        PROTOBUF_FIELD_OFFSET(::protocol::MsgACK_S, _impl_.msg_id_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protocol::GroupMsgNotify, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protocol::GroupMsgNotify, _impl_.group_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protocol::Packet)},
        {14, -1, -1, sizeof(::protocol::Msg)},
        {29, 40, -1, sizeof(::protocol::MsgACK_C)},
        {43, 53, -1, sizeof(::protocol::MsgACK_S)},
        {55, -1, -1, sizeof(::protocol::GroupMsgNotify)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protocol::_Packet_default_instance_._instance,
    &::protocol::_Msg_default_instance_._instance,
    &::protocol::_MsgACK_C_default_instance_._instance,
    &::protocol::_MsgACK_S_default_instance_._instance,
    &::protocol::_GroupMsgNotify_default_instance_._instance,
};
const char descriptor_table_protodef_protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016protocol.proto\022\010protocol\"j\n\006Packet\022\013\n\003"
    "seq\030\001 \001(\006\022\021\n\ttimestamp\030\002 \001(\006\022\013\n\003cmd\030\003 \001("
    "\007\022\020\n\010msg_type\030\004 \001(\007\022\023\n\013data_length\030\005 \001(\007"
    "\022\014\n\004data\030\006 \001(\014\"\217\001\n\003Msg\022\016\n\006msg_id\030\001 \001(\004\022\027"
    "\n\017conversation_id\030\002 \001(\004\022\021\n\tsender_id\030\003 \001"
    "(\004\022\023\n\013receiver_id\030\004 \001(\004\022\024\n\014content_type\030"
    "\005 \001(\r\022\020\n\010is_group\030\006 \001(\010\022\017\n\007content\030\007 \001(\014"
    "\"c\n\010MsgACK_C\022\013\n\003seq\030\001 \001(\004\022\024\n\007conv_id\030\002 \001"
    "(\004H\000\210\001\001\022\030\n\013last_msg_id\030\003 \001(\004H\001\210\001\001B\n\n\010_co"
    "nv_idB\016\n\014_last_msg_id\"7\n\010MsgACK_S\022\013\n\003seq"
    "\030\001 \001(\004\022\023\n\006msg_id\030\002 \001(\004H\000\210\001\001B\t\n\007_msg_id\"\""
    "\n\016GroupMsgNotify\022\020\n\010group_id\030\001 \001(\004b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protocol_2eproto = {
    false,
    false,
    482,
    descriptor_table_protodef_protocol_2eproto,
    "protocol.proto",
    &descriptor_table_protocol_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_protocol_2eproto::offsets,
    file_level_enum_descriptors_protocol_2eproto,
    file_level_service_descriptors_protocol_2eproto,
};
namespace protocol {
// ===================================================================

class Packet::_Internal {
 public:
};

Packet::Packet(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.Packet)
}
inline PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protocol::Packet& from_msg)
      : data_(arena, from.data_),
        _cached_size_{0} {}

Packet::Packet(
    ::google::protobuf::Arena* arena,
    const Packet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Packet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, seq_),
           offsetof(Impl_, data_length_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::data_length_));

  // @@protoc_insertion_point(copy_constructor:protocol.Packet)
}
inline PROTOBUF_NDEBUG_INLINE Packet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_(arena),
        _cached_size_{0} {}

inline void Packet::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_),
           0,
           offsetof(Impl_, data_length_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::data_length_));
}
Packet::~Packet() {
  // @@protoc_insertion_point(destructor:protocol.Packet)
  SharedDtor(*this);
}
inline void Packet::SharedDtor(MessageLite& self) {
  Packet& this_ = static_cast<Packet&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Packet::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Packet(arena);
}
constexpr auto Packet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Packet),
                                            alignof(Packet));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Packet::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Packet_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Packet::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Packet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Packet::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Packet>(), &Packet::ByteSizeLong,
            &Packet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Packet, _impl_._cached_size_),
        false,
    },
    &Packet::kDescriptorMethods,
    &descriptor_table_protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Packet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2> Packet::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::Packet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // fixed64 seq = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.seq_)}},
    // fixed64 timestamp = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.timestamp_)}},
    // fixed32 cmd = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.cmd_)}},
    // fixed32 msg_type = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.msg_type_)}},
    // fixed32 data_length = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.data_length_)}},
    // bytes data = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(Packet, _impl_.data_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // fixed64 seq = 1;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.seq_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed64)},
    // fixed64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed64)},
    // fixed32 cmd = 3;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.cmd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // fixed32 msg_type = 4;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.msg_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // fixed32 data_length = 5;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.data_length_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // bytes data = 6;
    {PROTOBUF_FIELD_OFFSET(Packet, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Packet::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Packet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.seq_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.data_length_) -
      reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.data_length_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Packet::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Packet::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.Packet)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // fixed64 seq = 1;
          if (this_._internal_seq() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed64ToArray(
                1, this_._internal_seq(), target);
          }

          // fixed64 timestamp = 2;
          if (this_._internal_timestamp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed64ToArray(
                2, this_._internal_timestamp(), target);
          }

          // fixed32 cmd = 3;
          if (this_._internal_cmd() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                3, this_._internal_cmd(), target);
          }

          // fixed32 msg_type = 4;
          if (this_._internal_msg_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                4, this_._internal_msg_type(), target);
          }

          // fixed32 data_length = 5;
          if (this_._internal_data_length() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                5, this_._internal_data_length(), target);
          }

          // bytes data = 6;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            target = stream->WriteBytesMaybeAliased(6, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.Packet)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Packet::ByteSizeLong(const MessageLite& base) {
          const Packet& this_ = static_cast<const Packet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Packet::ByteSizeLong() const {
          const Packet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.Packet)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes data = 6;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_data());
            }
            // fixed64 seq = 1;
            if (this_._internal_seq() != 0) {
              total_size += 9;
            }
            // fixed64 timestamp = 2;
            if (this_._internal_timestamp() != 0) {
              total_size += 9;
            }
            // fixed32 cmd = 3;
            if (this_._internal_cmd() != 0) {
              total_size += 5;
            }
            // fixed32 msg_type = 4;
            if (this_._internal_msg_type() != 0) {
              total_size += 5;
            }
            // fixed32 data_length = 5;
            if (this_._internal_data_length() != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Packet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Packet*>(&to_msg);
  auto& from = static_cast<const Packet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.Packet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_seq() != 0) {
    _this->_impl_.seq_ = from._impl_.seq_;
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  if (from._internal_cmd() != 0) {
    _this->_impl_.cmd_ = from._impl_.cmd_;
  }
  if (from._internal_msg_type() != 0) {
    _this->_impl_.msg_type_ = from._impl_.msg_type_;
  }
  if (from._internal_data_length() != 0) {
    _this->_impl_.data_length_ = from._impl_.data_length_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Packet::CopyFrom(const Packet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Packet::InternalSwap(Packet* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Packet, _impl_.data_length_)
      + sizeof(Packet::_impl_.data_length_)
      - PROTOBUF_FIELD_OFFSET(Packet, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

::google::protobuf::Metadata Packet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Msg::_Internal {
 public:
};

Msg::Msg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.Msg)
}
inline PROTOBUF_NDEBUG_INLINE Msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protocol::Msg& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

Msg::Msg(
    ::google::protobuf::Arena* arena,
    const Msg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Msg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msg_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, msg_id_),
           offsetof(Impl_, is_group_) -
               offsetof(Impl_, msg_id_) +
               sizeof(Impl_::is_group_));

  // @@protoc_insertion_point(copy_constructor:protocol.Msg)
}
inline PROTOBUF_NDEBUG_INLINE Msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void Msg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msg_id_),
           0,
           offsetof(Impl_, is_group_) -
               offsetof(Impl_, msg_id_) +
               sizeof(Impl_::is_group_));
}
Msg::~Msg() {
  // @@protoc_insertion_point(destructor:protocol.Msg)
  SharedDtor(*this);
}
inline void Msg::SharedDtor(MessageLite& self) {
  Msg& this_ = static_cast<Msg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Msg::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Msg(arena);
}
constexpr auto Msg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Msg),
                                            alignof(Msg));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Msg::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Msg_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Msg::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Msg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Msg::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Msg>(), &Msg::ByteSizeLong,
            &Msg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Msg, _impl_._cached_size_),
        false,
    },
    &Msg::kDescriptorMethods,
    &descriptor_table_protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Msg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2> Msg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::Msg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 msg_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Msg, _impl_.msg_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.msg_id_)}},
    // uint64 conversation_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Msg, _impl_.conversation_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.conversation_id_)}},
    // uint64 sender_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Msg, _impl_.sender_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.sender_id_)}},
    // uint64 receiver_id = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Msg, _impl_.receiver_id_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.receiver_id_)}},
    // uint32 content_type = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Msg, _impl_.content_type_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.content_type_)}},
    // bool is_group = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Msg, _impl_.is_group_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.is_group_)}},
    // bytes content = 7;
    {::_pbi::TcParser::FastBS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(Msg, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 msg_id = 1;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.msg_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 conversation_id = 2;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.conversation_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 sender_id = 3;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.sender_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 receiver_id = 4;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.receiver_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 content_type = 5;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.content_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool is_group = 6;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.is_group_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bytes content = 7;
    {PROTOBUF_FIELD_OFFSET(Msg, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Msg::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Msg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  ::memset(&_impl_.msg_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_group_) -
      reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.is_group_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Msg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Msg& this_ = static_cast<const Msg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Msg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Msg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.Msg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 msg_id = 1;
          if (this_._internal_msg_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_msg_id(), target);
          }

          // uint64 conversation_id = 2;
          if (this_._internal_conversation_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_conversation_id(), target);
          }

          // uint64 sender_id = 3;
          if (this_._internal_sender_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                3, this_._internal_sender_id(), target);
          }

          // uint64 receiver_id = 4;
          if (this_._internal_receiver_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_receiver_id(), target);
          }

          // uint32 content_type = 5;
          if (this_._internal_content_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_content_type(), target);
          }

          // bool is_group = 6;
          if (this_._internal_is_group() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_is_group(), target);
          }

          // bytes content = 7;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            target = stream->WriteBytesMaybeAliased(7, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.Msg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Msg::ByteSizeLong(const MessageLite& base) {
          const Msg& this_ = static_cast<const Msg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Msg::ByteSizeLong() const {
          const Msg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.Msg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes content = 7;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_content());
            }
            // uint64 msg_id = 1;
            if (this_._internal_msg_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_msg_id());
            }
            // uint64 conversation_id = 2;
            if (this_._internal_conversation_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_conversation_id());
            }
            // uint64 sender_id = 3;
            if (this_._internal_sender_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_sender_id());
            }
            // uint64 receiver_id = 4;
            if (this_._internal_receiver_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_receiver_id());
            }
            // uint32 content_type = 5;
            if (this_._internal_content_type() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_content_type());
            }
            // bool is_group = 6;
            if (this_._internal_is_group() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Msg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Msg*>(&to_msg);
  auto& from = static_cast<const Msg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.Msg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_msg_id() != 0) {
    _this->_impl_.msg_id_ = from._impl_.msg_id_;
  }
  if (from._internal_conversation_id() != 0) {
    _this->_impl_.conversation_id_ = from._impl_.conversation_id_;
  }
  if (from._internal_sender_id() != 0) {
    _this->_impl_.sender_id_ = from._impl_.sender_id_;
  }
  if (from._internal_receiver_id() != 0) {
    _this->_impl_.receiver_id_ = from._impl_.receiver_id_;
  }
  if (from._internal_content_type() != 0) {
    _this->_impl_.content_type_ = from._impl_.content_type_;
  }
  if (from._internal_is_group() != 0) {
    _this->_impl_.is_group_ = from._impl_.is_group_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Msg::CopyFrom(const Msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Msg::InternalSwap(Msg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Msg, _impl_.is_group_)
      + sizeof(Msg::_impl_.is_group_)
      - PROTOBUF_FIELD_OFFSET(Msg, _impl_.msg_id_)>(
          reinterpret_cast<char*>(&_impl_.msg_id_),
          reinterpret_cast<char*>(&other->_impl_.msg_id_));
}

::google::protobuf::Metadata Msg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MsgACK_C::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MsgACK_C>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_._has_bits_);
};

MsgACK_C::MsgACK_C(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.MsgACK_C)
}
MsgACK_C::MsgACK_C(
    ::google::protobuf::Arena* arena, const MsgACK_C& from)
    : MsgACK_C(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MsgACK_C::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MsgACK_C::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_),
           0,
           offsetof(Impl_, last_msg_id_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::last_msg_id_));
}
MsgACK_C::~MsgACK_C() {
  // @@protoc_insertion_point(destructor:protocol.MsgACK_C)
  SharedDtor(*this);
}
inline void MsgACK_C::SharedDtor(MessageLite& self) {
  MsgACK_C& this_ = static_cast<MsgACK_C&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MsgACK_C::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MsgACK_C(arena);
}
constexpr auto MsgACK_C::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MsgACK_C),
                                            alignof(MsgACK_C));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MsgACK_C::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MsgACK_C_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MsgACK_C::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MsgACK_C>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MsgACK_C::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MsgACK_C>(), &MsgACK_C::ByteSizeLong,
            &MsgACK_C::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_._cached_size_),
        false,
    },
    &MsgACK_C::kDescriptorMethods,
    &descriptor_table_protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MsgACK_C::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> MsgACK_C::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::MsgACK_C>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 seq = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgACK_C, _impl_.seq_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.seq_)}},
    // optional uint64 conv_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgACK_C, _impl_.conv_id_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.conv_id_)}},
    // optional uint64 last_msg_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgACK_C, _impl_.last_msg_id_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.last_msg_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 seq = 1;
    {PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.seq_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // optional uint64 conv_id = 2;
    {PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.conv_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 last_msg_id = 3;
    {PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.last_msg_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MsgACK_C::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.MsgACK_C)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.seq_ = ::uint64_t{0u};
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.conv_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.last_msg_id_) -
        reinterpret_cast<char*>(&_impl_.conv_id_)) + sizeof(_impl_.last_msg_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MsgACK_C::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MsgACK_C& this_ = static_cast<const MsgACK_C&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MsgACK_C::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MsgACK_C& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.MsgACK_C)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 seq = 1;
          if (this_._internal_seq() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_seq(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional uint64 conv_id = 2;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_conv_id(), target);
          }

          // optional uint64 last_msg_id = 3;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                3, this_._internal_last_msg_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.MsgACK_C)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MsgACK_C::ByteSizeLong(const MessageLite& base) {
          const MsgACK_C& this_ = static_cast<const MsgACK_C&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MsgACK_C::ByteSizeLong() const {
          const MsgACK_C& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.MsgACK_C)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 seq = 1;
            if (this_._internal_seq() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_seq());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional uint64 conv_id = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_conv_id());
            }
            // optional uint64 last_msg_id = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_last_msg_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MsgACK_C::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MsgACK_C*>(&to_msg);
  auto& from = static_cast<const MsgACK_C&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.MsgACK_C)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _this->_impl_.seq_ = from._impl_.seq_;
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.conv_id_ = from._impl_.conv_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.last_msg_id_ = from._impl_.last_msg_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MsgACK_C::CopyFrom(const MsgACK_C& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.MsgACK_C)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MsgACK_C::InternalSwap(MsgACK_C* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.last_msg_id_)
      + sizeof(MsgACK_C::_impl_.last_msg_id_)
      - PROTOBUF_FIELD_OFFSET(MsgACK_C, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

::google::protobuf::Metadata MsgACK_C::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MsgACK_S::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MsgACK_S>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_._has_bits_);
};

MsgACK_S::MsgACK_S(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.MsgACK_S)
}
MsgACK_S::MsgACK_S(
    ::google::protobuf::Arena* arena, const MsgACK_S& from)
    : MsgACK_S(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MsgACK_S::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MsgACK_S::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_),
           0,
           offsetof(Impl_, msg_id_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::msg_id_));
}
MsgACK_S::~MsgACK_S() {
  // @@protoc_insertion_point(destructor:protocol.MsgACK_S)
  SharedDtor(*this);
}
inline void MsgACK_S::SharedDtor(MessageLite& self) {
  MsgACK_S& this_ = static_cast<MsgACK_S&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MsgACK_S::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MsgACK_S(arena);
}
constexpr auto MsgACK_S::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MsgACK_S),
                                            alignof(MsgACK_S));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MsgACK_S::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MsgACK_S_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MsgACK_S::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MsgACK_S>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MsgACK_S::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MsgACK_S>(), &MsgACK_S::ByteSizeLong,
            &MsgACK_S::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_._cached_size_),
        false,
    },
    &MsgACK_S::kDescriptorMethods,
    &descriptor_table_protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MsgACK_S::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MsgACK_S::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::MsgACK_S>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint64 msg_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgACK_S, _impl_.msg_id_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.msg_id_)}},
    // uint64 seq = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MsgACK_S, _impl_.seq_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.seq_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 seq = 1;
    {PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.seq_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // optional uint64 msg_id = 2;
    {PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.msg_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MsgACK_S::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.MsgACK_S)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.seq_ = ::uint64_t{0u};
  _impl_.msg_id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MsgACK_S::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MsgACK_S& this_ = static_cast<const MsgACK_S&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MsgACK_S::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MsgACK_S& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.MsgACK_S)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 seq = 1;
          if (this_._internal_seq() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_seq(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional uint64 msg_id = 2;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_msg_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.MsgACK_S)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MsgACK_S::ByteSizeLong(const MessageLite& base) {
          const MsgACK_S& this_ = static_cast<const MsgACK_S&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MsgACK_S::ByteSizeLong() const {
          const MsgACK_S& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.MsgACK_S)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 seq = 1;
            if (this_._internal_seq() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_seq());
            }
          }
           {
            // optional uint64 msg_id = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_msg_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MsgACK_S::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MsgACK_S*>(&to_msg);
  auto& from = static_cast<const MsgACK_S&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.MsgACK_S)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_seq() != 0) {
    _this->_impl_.seq_ = from._impl_.seq_;
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.msg_id_ = from._impl_.msg_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MsgACK_S::CopyFrom(const MsgACK_S& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.MsgACK_S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MsgACK_S::InternalSwap(MsgACK_S* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.msg_id_)
      + sizeof(MsgACK_S::_impl_.msg_id_)
      - PROTOBUF_FIELD_OFFSET(MsgACK_S, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

::google::protobuf::Metadata MsgACK_S::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GroupMsgNotify::_Internal {
 public:
};

GroupMsgNotify::GroupMsgNotify(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protocol.GroupMsgNotify)
}
GroupMsgNotify::GroupMsgNotify(
    ::google::protobuf::Arena* arena, const GroupMsgNotify& from)
    : GroupMsgNotify(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GroupMsgNotify::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GroupMsgNotify::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.group_id_ = {};
}
GroupMsgNotify::~GroupMsgNotify() {
  // @@protoc_insertion_point(destructor:protocol.GroupMsgNotify)
  SharedDtor(*this);
}
inline void GroupMsgNotify::SharedDtor(MessageLite& self) {
  GroupMsgNotify& this_ = static_cast<GroupMsgNotify&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GroupMsgNotify::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GroupMsgNotify(arena);
}
constexpr auto GroupMsgNotify::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GroupMsgNotify),
                                            alignof(GroupMsgNotify));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GroupMsgNotify::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GroupMsgNotify_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GroupMsgNotify::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GroupMsgNotify>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GroupMsgNotify::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GroupMsgNotify>(), &GroupMsgNotify::ByteSizeLong,
            &GroupMsgNotify::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GroupMsgNotify, _impl_._cached_size_),
        false,
    },
    &GroupMsgNotify::kDescriptorMethods,
    &descriptor_table_protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GroupMsgNotify::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GroupMsgNotify::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protocol::GroupMsgNotify>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 group_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GroupMsgNotify, _impl_.group_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GroupMsgNotify, _impl_.group_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 group_id = 1;
    {PROTOBUF_FIELD_OFFSET(GroupMsgNotify, _impl_.group_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GroupMsgNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.GroupMsgNotify)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.group_id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GroupMsgNotify::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GroupMsgNotify& this_ = static_cast<const GroupMsgNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GroupMsgNotify::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GroupMsgNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protocol.GroupMsgNotify)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 group_id = 1;
          if (this_._internal_group_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_group_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protocol.GroupMsgNotify)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GroupMsgNotify::ByteSizeLong(const MessageLite& base) {
          const GroupMsgNotify& this_ = static_cast<const GroupMsgNotify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GroupMsgNotify::ByteSizeLong() const {
          const GroupMsgNotify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protocol.GroupMsgNotify)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint64 group_id = 1;
            if (this_._internal_group_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_group_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GroupMsgNotify::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GroupMsgNotify*>(&to_msg);
  auto& from = static_cast<const GroupMsgNotify&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protocol.GroupMsgNotify)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_group_id() != 0) {
    _this->_impl_.group_id_ = from._impl_.group_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GroupMsgNotify::CopyFrom(const GroupMsgNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.GroupMsgNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GroupMsgNotify::InternalSwap(GroupMsgNotify* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.group_id_, other->_impl_.group_id_);
}

::google::protobuf::Metadata GroupMsgNotify::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
