server:
  name: "user"
  id: "user1"
  port: 9000
  file_save_relative_path: "."
consul:
  host: "127.0.0.1"
  port: 8500

mysql:
  host: "127.0.0.1"
  port: 3306
  user:
  password:
  db: "IM"
  max_connections: 10
  max_idle_connections: 5

redis:
  host: "127.0.0.1"
  port: 6379
  password:
  db: 0

email:
  host: "smtp.qq.com"
  port: 587
  from:
  password: